/**
 * The managed section is the part of ~/.ssh/config that Lanyard owns and
 * regenerates from state.json. It always sits at the very top of the file so
 * that its IdentityFile entries are offered before anything the user defines.
 */

import type { ManagedEntry } from './model';

export const BEGIN = '# >>> lanyard managed section >>>';
export const END = '# <<< lanyard managed section <<<';

/** Markers written before the rename; still recognised so old configs migrate in place. */
export const LEGACY_BEGIN = '# >>> sshm managed section >>>';
export const LEGACY_END = '# <<< sshm managed section <<<';

const QUOTED_KEYS = new Set(['identityfile', 'certificatefile', 'identityagent', 'controlpath']);

/** Quote values that may contain spaces where ssh expects a single token. */
export function formatValue(key: string, value: unknown): string {
  const v = String(value ?? '').trim();
  if (QUOTED_KEYS.has(key.toLowerCase()) && /\s/.test(v) && !/^".*"$/.test(v)) return `"${v}"`;
  return v;
}

/**
 * Render managed entries into lines. The section ends with a bare "Host *" so
 * global directives in the user's part of the file (which follows) keep
 * applying to every host instead of being swallowed by the last managed block.
 */
export function renderManaged(entries: ManagedEntry[]): string[] {
  if (!entries.length) return [];
  const out = [
    BEGIN,
    '# Generated by Lanyard. Change these entries from the app or the',
    '# `lanyard` CLI - manual edits inside this section are overwritten.',
    '',
  ];
  for (const e of entries) {
    for (const c of e.comment.split('\n').filter(Boolean)) out.push(`# ${c}`);
    out.push(`Host ${e.patterns}`);
    for (const o of e.options) out.push(`    ${o.key} ${formatValue(o.key, o.value)}`);
    out.push('');
  }
  out.push('# Reset scope: everything below applies to all hosts again.');
  out.push('Host *');
  out.push(END);
  return out;
}
