'use strict';

/**
 * The managed section is the part of ~/.ssh/config that sshm owns and
 * regenerates from state.json. It always sits at the very top of the file so
 * that its IdentityFile entries are offered before anything the user defines.
 */

const BEGIN = '# >>> sshm managed section >>>';
const END = '# <<< sshm managed section <<<';

const QUOTED_KEYS = new Set(['identityfile', 'certificatefile', 'identityagent', 'controlpath']);

/** Quote values that may contain spaces where ssh expects a single token. */
function formatValue(key, value) {
  const v = String(value ?? '').trim();
  if (QUOTED_KEYS.has(key.toLowerCase()) && /\s/.test(v) && !/^".*"$/.test(v)) return `"${v}"`;
  return v;
}

/**
 * Render managed entries ({ comment, patterns, options }) into lines. The
 * section ends with a bare "Host *" so global directives in the user's part of
 * the file (which follows) keep applying to every host instead of being
 * swallowed by the last managed block.
 */
function renderManaged(entries) {
  if (!entries.length) return [];
  const out = [
    BEGIN,
    '# Generated by SSH Manager (sshm). Change these entries from the app or the',
    '# `sshm` CLI - manual edits inside this section are overwritten.',
    '',
  ];
  for (const e of entries) {
    for (const c of String(e.comment || '').split('\n').filter(Boolean)) out.push(`# ${c}`);
    out.push(`Host ${e.patterns}`);
    for (const o of e.options) out.push(`    ${o.key} ${formatValue(o.key, o.value)}`);
    out.push('');
  }
  out.push('# Reset scope: everything below applies to all hosts again.');
  out.push('Host *');
  out.push(END);
  return out;
}

module.exports = { BEGIN, END, formatValue, renderManaged };
